### ISSUE TITLE
No way to set Universe in "Node Map" tab

### ISSUE THREAD

**Issue by tschundler** [spectrenoir06/LED_master#1]
The ArtNet output references `self.uni` to match the universe to the configured outputs, but there is no way to set the `uni`verse in the UI, only in .map JSON file

Example in the .map that required manual editing:

```
	"nodes":[
		{
			"net":      0,
			"subnet":   0,
			"uni":      0,
			"ip":       "192.168.1.31",
			"port":     6454,
			"rgbw":     false,
			"protocol": "artnet",
			"led_nb":   160,
		},
		{
			"net":      0,
			"subnet":   0,
			"uni":      1,
			"ip":       "192.168.1.31",
			"port":     6454,
			"rgbw":     false,
			"protocol": "artnet",
			"led_nb":   160,
		},
      ]
```

**Comment by spectrenoir06** [comment]
I need to finish the art-net ( net / sub-net / uni )
right now i think the subnet UI are the universe
