### ISSUE TITLE
ArtNet outputs more data than needed (sometimes a lot more)

### ISSUE THREAD

**Issue by tschundler** [spectrenoir06/LED_master#2]
I have `led_nb` set to the number of LEDs per universe. (for me, 160) But the artnet packets have 510 channels always, even if only sending a single LED.
Sometimes it sends 510 channels and also an extra 170 bytes of empty data 0x00. (hm... maybe it did rgbw * typical 170 LEDs? I'm guessing `170` is hardcoded somewhere it shouldn't be)
It should probably send `led_nb` * channels per pixel, or simply up to the highest number that was set.

(This is low priority as it doesn't break anything, but just wastes bandwidth in an already wasteful protocol)

**Comment by spectrenoir06** [comment]
You can also add manu

**Comment by spectrenoir06** [comment]
Ok it's fix.
you can use the protocol artnet and add node with led_nb = 160
it will only send 480 channels in RGB mode
```
{
	"net":      0,
	"subnet":   0,
	"uni":      0,
	"ip":       "10.0.0.106",
	"port":     6454,
	"rgbw":     false,
	"protocol": "artnet",
	"led_nb":   160,
},
{
	"net":      0,
	"subnet":   0,
	"uni":      1,
	"ip":       "10.0.0.106",
	"port":     6454,
	"rgbw":     false,
	"protocol": "artnet",
	"led_nb":   160,
},
```

But if you have multiple artnet node and you are lazy you can also use artnet_big
you only need to add 1 node with led_nb = total number of led
and manually add leds_by_uni to the map file.

be careful when you edit map file.
try to edit the map file here https://github.com/spectrenoir06/LED_master#add-ressource

```
{
	"net":      0,
	"subnet":   0,
	"uni":      1,
	"ip":       "10.0.0.106",
	"port":     6454,
	"rgbw":     false,
	"protocol": "artnet_big",
	"leds_by_uni": 100,
	"led_nb":   500,
},
```
